"""
rule_engine.py

Deterministic compliance guardrail that WRAPS the bandit.

Card network retry caps are a hard constraint, not something we want the
bandit to "learn" to respect via reward signals -- a bandit could still
burn a merchant's last permitted attempt while exploring. So this layer
sits outside the bandit entirely:

    - It tracks how many automated API retry attempts each transaction
      has used.
    - It looks up the ACTUAL applicable cap for that transaction's
      payment network + decline category (see "Research-grounded caps"
      below) -- not one generic global number.
    - Once a transaction is at/near its applicable cap, it FORCES the
      decision to whatsapp_escalate, without even asking the bandit.
    - As the cap gets close (exactly 1 attempt remaining), it also
      narrows what the bandit is even ALLOWED to choose from -- see
      "Soft zone" below.
    - Otherwise, it lets the bandit choose freely among all arms.

whatsapp_escalate never counts against the network retry cap -- it isn't
hitting the card network at all, so it doesn't carry the same compliance
risk as another API retry attempt.

This is the piece that makes the "compliant escalation + stopping rules"
claim demonstrable rather than decorative: every decision this module
makes is either "bandit choice" or "rule engine override", and that flag
is exactly what audit_log.py records.

Research-grounded caps (not invented numbers):
    - UPI_AUTOPAY: NPCI's August 2025 Autopay guidelines standardize
      retries to "1 original attempt + up to 3 retries" per mandate
      execution cycle.
    - Visa: the "Excessive Reattempts Rule" permits up to 15 reattempts
      within a rolling 30-day window for retry-eligible (soft) declines.
    - Mastercard: stricter than Visa, commonly cited around 10 retries
      in 30 days (Mastercard signals per-transaction via Merchant Advice
      Codes rather than publishing one single number).
    - RuPay: no separately published RuPay-specific cap was found;
      conservatively assumed to match the NPCI/UPI Autopay cap since
      NPCI governs RuPay too. Flagged as an assumption, not a sourced
      figure -- confirm against actual scheme rules in production.
    - HARD DECLINES get a cap of ZERO on every network, regardless of
      the network's normal cap. This mirrors Visa's published Category 1
      "Never Retry" rule (lost/stolen/closed card) and is applied
      uniformly here as a conservative default across all networks.
    The actual numbers live in ground_truth.json (network_retry_caps +
    hard_decline_error_codes), generated by data/generate_data.py --
    this module just looks them up per transaction.

Soft zone (arm exclusion near the cap):
    Once a transaction has exactly 1 API retry attempt left before the
    cap forces escalation, the rule engine excludes retry_72h from the
    bandit's choice set. Reasoning: committing your LAST permitted shot
    to a 3-day wait is a bad trade -- if it fails, you've burned days
    AND your last attempt, arriving at forced escalation later than if
    you'd tried something faster. This doesn't touch the bandit's
    learning (the excluded arm's posterior is untouched, just not
    offered THIS one time) -- it's a deterministic, explainable
    override, same category as the hard stop itself.

Risk-adjusted reward:
    This module also computes the risk_penalty fed into bandit.update().
    A failed API retry that burns a transaction's LAST permitted attempt
    (right before compliance forces a channel switch) hurts that arm's
    posterior more than an early failure with plenty of budget left --
    it cost something scarce, not just a missed conversion. The penalty
    scales with how little retry budget remained AFTER this attempt:

        scarcity_factor = 1 / (attempts_remaining_after + 1)
        risk_penalty    = RISK_PENALTY_WEIGHT * scarcity_factor

    whatsapp_escalate never gets a risk_penalty since it doesn't consume
    network-capped budget at all.

Revenue weighting:
    record_outcome() also accepts the transaction's amount and converts
    it into a revenue_weight (amount / AVERAGE_TRANSACTION_AMOUNT) passed
    to bandit.update(). An average-value transaction weighs ~1.0
    (unchanged behavior); a high-value transaction's outcome moves the
    posterior more, a low-value one moves it less -- so the bandit
    optimizes for rupees recovered, not just raw hit rate.
"""

from engine.bandit import SegmentedThompsonBandit

API_RETRY_ARMS = {"retry_2h", "retry_24h", "retry_72h"}
ESCALATION_ARM = "whatsapp_escalate"
LONG_WAIT_ARM = "retry_72h"  # excluded from the choice set in the "soft zone" (see module docstring)
RISK_PENALTY_WEIGHT = 1.0  # tunable: how strongly scarcity amplifies a failure's cost
# mean of data/generate_data.py's AMOUNT_BUCKETS -- an "average" transaction
# gets revenue_weight ~= 1.0 (unchanged behavior); update this if the
# amount distribution in generate_data.py changes meaningfully.
AVERAGE_TRANSACTION_AMOUNT = 1642

# Fallback cap used only if a network isn't found in the ground-truth
# table passed in (shouldn't happen in the demo, but keeps this module
# safe to use standalone / in tests without a full ground_truth.json).
DEFAULT_NETWORK_RETRY_CAP = 3


class RuleEngine:
    def __init__(self, bandit: SegmentedThompsonBandit, network_retry_caps: dict,
                 hard_decline_error_codes=None,
                 risk_penalty_weight: float = RISK_PENALTY_WEIGHT,
                 average_transaction_amount: float = AVERAGE_TRANSACTION_AMOUNT):
        """
        bandit: a SegmentedThompsonBandit instance (the "brain")
        network_retry_caps: dict of {payment_network: max_retries},
            e.g. {"UPI_AUTOPAY": 3, "Visa": 15, "Mastercard": 10, "RuPay": 3}
            -- comes from ground_truth.json's network_retry_caps in the
            demo (see module docstring for sourcing).
        hard_decline_error_codes: set/list of error_code values that
            represent a PERMANENT decline (card lost/stolen/closed) and
            therefore get a retry cap of ZERO regardless of network.
            Defaults to {"hard_decline"} if not provided.
        risk_penalty_weight: scales how strongly a failure that consumes
            scarce retry budget is penalized in the bandit's posterior
            (see module docstring). Defaults to RISK_PENALTY_WEIGHT.
        average_transaction_amount: used to normalize a transaction's
            amount into a revenue_weight (amount / this value) passed to
            the bandit -- see module docstring's "Revenue weighting"
            section. Defaults to AVERAGE_TRANSACTION_AMOUNT.
        """
        self.bandit = bandit
        self.network_retry_caps = network_retry_caps
        self.hard_decline_error_codes = set(hard_decline_error_codes or {"hard_decline"})
        self.risk_penalty_weight = risk_penalty_weight
        self.average_transaction_amount = average_transaction_amount
        # per-transaction attempt counters: { transaction_id: int }
        self.attempts_used = {}

    def _attempts_so_far(self, transaction_id):
        return self.attempts_used.get(transaction_id, 0)

    def get_applicable_cap(self, network, error_code):
        """
        Returns the actual retry cap for this (network, error_code)
        combination. Hard declines get 0 on every network -- see module
        docstring's "Research-grounded caps" section.
        """
        if error_code in self.hard_decline_error_codes:
            return 0
        return self.network_retry_caps.get(network, DEFAULT_NETWORK_RETRY_CAP)

    def decide(self, transaction_id, bank, error_code, network):
        """
        Decides the next recovery action for a transaction.

        network: the payment network/rail for this transaction (e.g.
            "UPI_AUTOPAY", "Visa", "Mastercard", "RuPay") -- determines
            which cap applies, alongside error_code (see
            get_applicable_cap).

        Returns a dict with everything the audit trail needs:
            {
                "arm": <chosen arm>,
                "source": "bandit" | "rule_engine_override",
                "attempts_used_before": int,
                "attempts_remaining": int,
                "applicable_cap": int,
                "excluded_arms": list (arms the rule engine removed from
                    consideration this decision, e.g. ["retry_72h"] in
                    the soft zone -- empty list if none),
                "sampled_values": dict or None (None when overridden,
                    since the bandit was never consulted),
            }
        """
        applicable_cap = self.get_applicable_cap(network, error_code)
        attempts_before = self._attempts_so_far(transaction_id)
        attempts_remaining = applicable_cap - attempts_before

        # HARD STOP: at or past the cap (includes hard declines, where
        # applicable_cap is 0, so this fires immediately on attempt 1) --
        # do not even consult the bandit.
        if attempts_remaining <= 0:
            return {
                "arm": ESCALATION_ARM,
                "source": "rule_engine_override",
                "attempts_used_before": attempts_before,
                "attempts_remaining": attempts_remaining,
                "applicable_cap": applicable_cap,
                "excluded_arms": [],
                "sampled_values": None,
            }

        # SOFT ZONE: exactly one attempt left before the hard stop --
        # don't let the bandit gamble that last shot on a 3-day wait.
        excluded_arms = []
        if attempts_remaining == 1:
            excluded_arms = [LONG_WAIT_ARM]

        chosen_arm, sampled_values = self.bandit.select_arm(bank, error_code, network, excluded_arms=excluded_arms)

        return {
            "arm": chosen_arm,
            "source": "bandit",
            "attempts_used_before": attempts_before,
            "attempts_remaining": attempts_remaining,
            "applicable_cap": applicable_cap,
            "excluded_arms": excluded_arms,
            "sampled_values": sampled_values,
        }

    def record_outcome(self, transaction_id, bank, error_code, network, arm, success: bool,
                        amount: float = None):
        """
        Records the real-world outcome of a chosen arm:
            - computes a risk_penalty (only relevant on failed API retry
              arms -- see module docstring) based on how little retry
              budget will remain AFTER this attempt is counted, relative
              to THIS transaction's applicable cap.
            - computes a revenue_weight from the transaction's amount.
              If amount is not provided, defaults to weight 1.0.
            - feeds the outcome + risk_penalty + revenue_weight back into
              the bandit's posterior so it learns.
            - increments the transaction's attempt counter, but ONLY if
              the arm actually counts against the network cap (i.e. it
              was an API retry arm, not whatsapp_escalate).
        """
        applicable_cap = self.get_applicable_cap(network, error_code)

        risk_penalty = 0.0
        if not success and arm in API_RETRY_ARMS:
            attempts_before = self._attempts_so_far(transaction_id)
            attempts_remaining_after = applicable_cap - (attempts_before + 1)
            scarcity_factor = 1.0 / (attempts_remaining_after + 1)
            risk_penalty = self.risk_penalty_weight * scarcity_factor

        revenue_weight = 1.0
        if amount is not None:
            revenue_weight = amount / self.average_transaction_amount

        self.bandit.update(bank, error_code, network, arm, success, risk_penalty=risk_penalty,
                            revenue_weight=revenue_weight)

        if arm in API_RETRY_ARMS:
            self.attempts_used[transaction_id] = self._attempts_so_far(transaction_id) + 1


if __name__ == "__main__":
    # smoke test 1: a soft-decline transaction on a STRICT rail
    # (UPI_AUTOPAY, cap=3) should walk through the soft zone (excluding
    # retry_72h on the last attempt) and then hard-stop at the cap.
    bandit = SegmentedThompsonBandit()
    caps = {"UPI_AUTOPAY": 3, "Visa": 15, "Mastercard": 10, "RuPay": 3}
    rule_engine = RuleEngine(bandit, network_retry_caps=caps)

    txn_id = "demo-txn-001"
    bank, error_code, network = "SBI", "insufficient_funds", "UPI_AUTOPAY"

    print(f"Simulating transaction {txn_id} ({bank}, {error_code}, {network})\n")

    for attempt in range(1, 6):  # deliberately go past the cap to prove the hard stop fires
        decision = rule_engine.decide(txn_id, bank, error_code, network)
        print(
            f"Attempt {attempt}: arm={decision['arm']:20s} "
            f"source={decision['source']:22s} "
            f"attempts_remaining={decision['attempts_remaining']} "
            f"excluded={decision['excluded_arms']}"
        )

        forced_success = False if decision["arm"] in API_RETRY_ARMS else True
        rule_engine.record_outcome(txn_id, bank, error_code, network, decision["arm"], forced_success)

        if decision["arm"] == ESCALATION_ARM:
            print("-> Escalated. Recovery attempt sequence ends here.\n")
            break

    # smoke test 2: a HARD DECLINE should escalate on attempt 1, even on
    # a lenient network like Visa (cap=15) -- because hard declines get
    # cap=0 regardless of network.
    txn_id_2 = "demo-txn-002"
    bank2, error_code2, network2 = "HDFC", "hard_decline", "Visa"
    print(f"Simulating transaction {txn_id_2} ({bank2}, {error_code2}, {network2}) -- hard decline on Visa (cap=15 normally)")
    decision2 = rule_engine.decide(txn_id_2, bank2, error_code2, network2)
    print(f"Attempt 1: arm={decision2['arm']:20s} source={decision2['source']:22s} "
          f"applicable_cap={decision2['applicable_cap']} (network cap is 15, but hard_decline forces 0)")
    assert decision2["arm"] == ESCALATION_ARM
    assert decision2["applicable_cap"] == 0
    print("Confirmed: hard decline escalates immediately regardless of the network's normal cap.")